import pandas as pd


order_info_df = pd.read_excel('C:/Users/donga/Desktop/AgencyTEAM/Data/task1.xlsx', sheet_name="secoo주문영문")
distribution_df = pd.read_excel('C:/Users/donga/Desktop/AgencyTEAM/Data/task1.xlsx', sheet_name="물류파일")

New_distribution_df = pd.DataFrame({'Shipment Reference No.': order_info_df["order No."],
                                    'Receiver Contact Name': order_info_df["customer name"],
                                    'Receiver Chinese Name': 'NULL',
                                    'Receiver Tel': order_info_df["customer phone"],
                                    'Receiver Address': order_info_df["detailed address"],
                                    'Receiver Province': order_info_df["province"],
                                    'Receiver Email': 'NULL',
                                    'Receiver Country/Region': 'China',
                                    'Receiver Credentials Type': 'ID',
                                    'Receiver Credentials No': order_info_df["certificates NO."],
                                    'Receiver Postal Code': order_info_df["vendor remark"],
                                    'Currency': 'CNY',
                                    'Shipment Type': 'International Economy Express – Parcel',
                                    'Add Service 1': 'NULL',
                                    'Add Service Account1': 'NULL',
                                    'Add Service Amount1': 'NULL',
                                    'Add Service2': 'NULL',
                                    'Add Service Account2': 'NULL',
                                    'Add Service Amount2': 'NULL',
                                    'Total Package': '1',
                                    'Self Pickup': 'NULL',
                                    'Payment Method': 'Shipper',
                                    'Account No.': '0825004317',
                                    'Third Party District Code': 'NULL',
                                    'Tax payment': 'Shipper',
                                    '(PCS)1': 'NULL',
                                    '(L)1': 'NULL',
                                    '(W)1': 'NULL',
                                    '(H)1': 'NULL',
                                    'Term of Trade': 'NULL',
                                    'Reason for Sending 1': 'NULL',
                                    'Reason for Sending 2': 'NULL',
                                    'Remarks': 'NULL',
                                    'AWB Remarks': 'NULL',
                                    'Tax Account': 'NULL',
                                    'Add Service3': 'NULL',
                                    'VAT': 'NULL',
                                    'EORI': 'NULL',
                                    'Traceability label': 'NULL',
                                    'PO Number': 'NULL',
                                    "Shipper's Tax ID No.": 'NULL',
                                    'Appointment Time': 'NULL',
                                    'Personal baggage': 'NULL',
                                    'Importer Company Name': 'NULL',
                                    'Importer Tel No.': 'NULL',
                                    'Importer Address': 'NULL',
                                    'Customs Clearance': 'NULL',
                                    'Shipper County': 'NULL',
                                    'Receiver County': 'NULL',
                                    'Shipper Credentials Type': 'NULL',
                                    'Shipper Credentials No.': 'NULL',
                                    'Notify to pick up': 'NO',
                                    'Formal Customs Declaration For import': 'NULL'
                                    })
#print(order_info_df["order No."])
#New_df = pd.DataFrame({'Shipment Reference No.' : order_info_df["order No."],
#                       'Receiver Email' : 'NULL'})
#print(New_distribution_df)
New_distribution_df.to_excel('C:/SS-workspace/task/AgencyTEAM/output/New_distribution_file.xlsx', index=False)
